#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
# install.sh — Install holographic memory patches for Nix Hermes
#
# Clones the patches into ~/.hermes/patches/ and sets up entry point wrappers
# that auto-discover Nix store paths.
#
# Usage:
#   ./install.sh                   # interactive, asks before overwriting
#   ./install.sh --force           # overwrite existing wrappers
#   ./install.sh --patches-only    # just copy patches, skip entry points
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
FORCE="${FORCE:-}"
PATCHES_ONLY="${PATCHES_ONLY:-}"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --force) FORCE=1; shift ;;
        --patches-only) PATCHES_ONLY=1; shift ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

echo "◆ holo-hermes installer"
echo ""

# ── Step 1: Find Nix Hermes ──────────────────────────────────────────────────

NIX_HERMES=""
for _p in ${PATH//:/ }; do
    _candidate="$_p/hermes"
    if [[ -f "$_candidate" && "$_candidate" != "$HOME/.local/bin/hermes" ]]; then
        NIX_HERMES="$_candidate"
        break
    fi
done

if [[ -z "$NIX_HERMES" ]]; then
    echo "✗ Cannot find Nix Hermes installation in PATH."
    echo "  Install Hermes first:  nix profile install github:NousResearch/hermes-agent"
    exit 1
fi

echo "✓ Found Hermes: $NIX_HERMES"

# Extract Python path from the bash wrapper
HERMES_PYTHON=$(grep -oP "HERMES_PYTHON='\K[^']*" "$NIX_HERMES" || true)
if [[ -z "$HERMES_PYTHON" ]]; then
    echo "✗ Could not extract HERMES_PYTHON from $NIX_HERMES"
    exit 1
fi
echo "✓ Hermes Python: $HERMES_PYTHON"

# ── Step 2: Copy patches ─────────────────────────────────────────────────────

PATCHES_SRC="$SCRIPT_DIR/patches"
PATCHES_DST="$HOME/.hermes/patches"

mkdir -p "$HOME/.hermes"
if [[ -d "$PATCHES_DST" ]]; then
    echo "  Patches directory already exists at $PATCHES_DST"
    echo "  Updating with rsync..."
    rsync -a --delete "$PATCHES_SRC/" "$PATCHES_DST/"
else
    cp -r "$PATCHES_SRC" "$PATCHES_DST"
fi
echo "✓ Patches installed at $PATCHES_DST"

# Strip __pycache__ from patches
find "$PATCHES_DST" -name __pycache__ -type d -exec rm -rf {} + 2>/dev/null || true

# ── Step 3: Create patched entry points (unless --patches-only) ───────────────

if [[ -n "$PATCHES_ONLY" ]]; then
    echo ""
    echo "✓ Done (patches only)."
    echo "  Connect them by setting up ~/.local/bin/hermes-agent and ~/.local/bin/hermes"
    echo "  (see README.md for manual steps, or re-run without --patches-only)."
    exit 0
fi

echo ""
echo "◆ Creating Hermes entry point wrappers in ~/.local/bin/"
mkdir -p "$HOME/.local/bin"

# ── 3a: hermes-agent (Python entry point) ─────────────────────────────────────

HERMES_AGENT_DST="$HOME/.local/bin/hermes-agent"

if [[ -f "$HERMES_AGENT_DST" ]] && [[ -z "$FORCE" ]]; then
    echo "  WARNING: $HERMES_AGENT_DST already exists."
    echo "  Overwrite? [y/N] "
    read -r _ans
    if [[ ! "$_ans" =~ ^[yY] ]]; then
        echo "  Skipping hermes-agent."
        SKIP_AGENT=1
    fi
fi

if [[ -z "${SKIP_AGENT:-}" ]]; then
    cat > "$HERMES_AGENT_DST" << 'PYEOF'
#!/usr/bin/env python3
"""Patched entry point — inserts ~/.hermes/patches into sys.path before
the real CLI loads, so our custom modules take precedence over originals."""
import os
import sys

patch_dir = os.path.expanduser("~/.hermes/patches")
if patch_dir not in sys.path:
    sys.path.insert(0, patch_dir)

from hermes_cli.main import main

if __name__ == "__main__":
    sys.exit(main())
PYEOF
    chmod +x "$HERMES_AGENT_DST"
    echo "✓ Created $HERMES_AGENT_DST"
fi

# ── 3b: hermes (bash wrapper) ────────────────────────────────────────────────

HERMES_DST="$HOME/.local/bin/hermes"

if [[ -f "$HERMES_DST" ]] && [[ -z "$FORCE" ]]; then
    echo "  WARNING: $HERMES_DST already exists."
    echo "  Overwrite? [y/N] "
    read -r _ans
    if [[ ! "$_ans" =~ ^[yY] ]]; then
        echo "  Skipping hermes bash wrapper."
        SKIP_WRAPPER=1
    fi
fi

if [[ -z "${SKIP_WRAPPER:-}" ]]; then
    # Extract all env vars and PATH additions from the Nix wrapper
    _env_block=$(grep -oP 'export (HERMES_\w+)='\''[^'\'']*'\''' "$NIX_HERMES" || true)
    _path_block=$(grep -oP 'PATH=\$PATH'\''[^'\'']*'\''' "$NIX_HERMES" || true)

    cat > "$HERMES_DST" << BEOF
#!/usr/bin/env bash
# Wrapper that launches Hermes with the patched background_review.py.
# Inserts ~/.hermes/patches into sys.path via patched entry point
# before run_agent loads.
#
# Auto-generated by holo-hermes install.sh

# --- Env vars from the Nix Hermes bash wrapper ---
${_env_block}

# --- PATH additions ---
${_path_block}
export PATH

PATCHED_ENTRY="$HOME/.local/bin/hermes-agent"

exec "$HERMES_PYTHON" "$PATCHED_ENTRY" "\$@"
BEOF
    chmod +x "$HERMES_DST"
    echo "✓ Created $HERMES_DST"
fi

# ── Step 4: Auto-configure ~/.hermes/config.yaml ───────────────────────────────

echo ""
echo "◆ Configuring ~/.hermes/config.yaml..."

"$HERMES_PYTHON" -c "
import os, yaml

config_path = os.path.expanduser('~/.hermes/config.yaml')

# Load existing config or start fresh
if os.path.exists(config_path):
    with open(config_path) as f:
        config = yaml.safe_load(f) or {}
else:
    config = {}

# Track what changed
changes = []

# Merge memory section
mem = config.setdefault('memory', {})
for key, val in [('memory_enabled', False), ('user_profile_enabled', False),
                  ('provider', 'holographic'), ('nudge_interval', 1)]:
    old = mem.get(key)
    mem[key] = val
    if old != val:
        changes.append(f'  memory.{key}: {old} -> {val}' if old is not None else f'  memory.{key}: {val}')

# Merge plugins section
plugins = config.setdefault('plugins', {})
hms = plugins.setdefault('hermes-memory-store', {})
for key, val in [('auto_extract', True), ('min_trust_threshold', 0.1)]:
    old = hms.get(key)
    hms[key] = val
    if old != val:
        changes.append(f'  plugins.hermes-memory-store.{key}: {old} -> {val}' if old is not None else f'  plugins.hermes-memory-store.{key}: {val}')

with open(config_path, 'w') as f:
    yaml.dump(config, f, default_flow_style=False, sort_keys=False)

if changes:
    print('  Updated:')
    for c in changes:
        print(c)
else:
    print('  Already configured — no changes needed.')
" 2>&1

echo "✓ Config updated at ~/.hermes/config.yaml"

echo ""
echo "✓ Install complete. Run: hermes"
echo ""
echo "NOTE: If 'hermes' command not found after install, add ~/.local/bin to your PATH:"
echo '  export PATH="$HOME/.local/bin:$PATH"'
echo "  (Add to ~/.bashrc or ~/.profile to make it permanent)"
